CREATE TABLE Author
(
    id         SERIAL PRIMARY KEY,
    full_name  VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE budget
    ADD COLUMN author_id INTEGER REFERENCES Author (id);
